import type { Metadata } from "next";
import "./globals.css";
import { MSWComponent } from "./_components/msw/MSWComponent";
import localFont from "next/font/local";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 프리텐다드 font-family
const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable}`}
      >
        <SessionProvider>
          <MSWComponent>
            {children}
          </MSWComponent>
        </SessionProvider>
      </body>
    </html>
  );
}